[build]
    command = "npm run build"

  [deploy]
    command = "npm start"

  [env]
    NEXT_PUBLIC_SUPABASE_URL = "${{NEXT_PUBLIC_SUPABASE_URL}}"
    NEXT_PUBLIC_SUPABASE_ANON_KEY =
  "${{NEXT_PUBLIC_SUPABASE_ANON_KEY}}"
    SUPABASE_SERVICE_ROLE_KEY = "${{SUPABASE_SERVICE_ROLE_KEY}}"
